### ISSUE TITLE
Fix for Language Server constantly crashing

### ISSUE THREAD

**Issue by w00tyd00d** [WingedSeal/JMC-Syntax-Highlighting#11]
If short circuit evaluation is added to line 184 in `data/helpers/general.ts`, it should fix the language server from constantly crashing in VSCode.

Change:
```ts
while (lexer.tokens[i].type != TokenType.LPAREN)
```
to
```ts
while (lexer.tokens[i] && lexer.tokens[i].type != TokenType.LPAREN)
```

I've changed it locally and it seems to have done the trick for me.

**Comment by Nico314159** [comment]
I believe he's rewriting the whole thing in C#

**Comment by bdke** [comment]
i am rewriting the whole things

**Comment by bdke** [comment]
Fixed
