### ISSUE TITLE
Extention not opening

### ISSUE THREAD

**Issue by ammaanm** [WingedSeal/JMC-Syntax-Highlighting#14]
The VS code output

```
[Error - 8:47:23 PM] Starting client failed
Launching server using command c:\Users\MyUsername\.vscode\extensions\wingedseal.jmc-4.0.0\out\src\server\JMCServer.exe failed.
```

I checked the  `c:\Users\MyUsername\.vscode\extensions\wingedseal.jmc-4.0.0\out\src` folder and it has only `extension.js` file, no folder or anything else. I think it can be because i use python version, but i dont know.

**Comment by bdke** [comment]
gonna rewrite the whole thing
